# basic information
[meta]
application_name = "lightbulb"
scenario_name = "default_scenario"
server_name = "default_server"

# env settings
[env]
debug = true
env = "dev"
log_level = "trace"

# device server setting
[server]
server_id = "deviceserver_dev"
server_ip = "127.0.0.1"
server_type = "deviceserver"


# bounding http server port
[web]
web_host = "0.0.0.0"
web_port = 5008

# pm2 守护进程名称（用于重启）
[pm2]
process_name = "device"

# mqtt information
[mqtt]
broker_host = "127.0.0.1"
broker_port = 1883
client_id = "lightbulb-device-engine-2335"


# upstream flowserver setting
[upstream]
host = "127.0.0.1"
port = 7001